this.paramDescriptors = [
    {
        name: 'file',
        label: 'File',
        type: 'integer',
        min: 0,
        max: 1000,
        default: 0,
        defaultstep: 1,
        path: `LAYER #/FILE SELECT/Value`,
        unit: '',
    },
    {
        name: 'folder',
        label: 'Folder',
        type: 'integer',
        min: 0,
        max: 1000,
        default: 0.0,
        defaultstep: 1,
        path: `LAYER #/FOLDER SELECT/Value`,
        unit: '',
    },
    {
        name: 'intensity',
        label: 'Intensity',
        type: 'range',
        min: 0,
        max: 100,
        default: 1.0,
        defaultstep: 10,
        path: `LAYER #/INTENSITY/Value`,
        unit: '%',
    },
    {
        name: 'inframe',
        label: 'In Frame',
        type: 'integer',
        min: 0,
        max: 9999999,
        default: 0.0,
        defaultstep: 30,
        path: `LAYER #/IN FRAME/Value`,
        unit: '',
    },
    {
        name: 'outframe',
        label: 'Out Frame',
        type: 'integer',
        min: 0,
        max: 9999999,
        default: 9999999.0,
        defaultstep: 30,
        path: `LAYER #/OUT FRAME/Value`,
        unit: '',
    },
    {
        name: 'playmode',
        type: 'select',
        label: 'Playmode',
        options: [
            { value: 0, label: 'In Frame' },
            { value: 1, label: 'Out Frame' },
            { value: 2, label: 'Loop Forwards' },
            { value: 3, label: 'Loop Reverse' },
            { value: 4, label: 'Play Once Forwards' },
            { value: 5, label: 'Play Once Reverse' },
            { value: 6, label: 'Stop' },
            { value: 7, label: 'Pause' },
            { value: 8, label: 'Bounce' },
            { value: 9, label: 'Take Over Frame' },
            { value: 10, label: 'Loop Forward Pause I=0' },
            { value: 11, label: 'Loop Reverse Pause I=0' },
            { value: 12, label: 'Play Once Forward Pause I=0' },
            { value: 13, label: 'Play Once Reverse Pause I=0' },
            { value: 15, label: 'Bounce Pause I=0' },
            { value: 20, label: 'Timecode Sync' },
            { value: 40, label: 'Loop Forward Re-Trigger I>0' },
            { value: 41, label: 'Loop Reverse Re-Trigger I>0' },
            { value: 42, label: 'Play Once Forward Re-Trigger I>0' },
            { value: 43, label: 'Play Once Reverse Re-Trigger I>0' },
            { value: 45, label: 'Bounce Re-Trigger I>0' },
        ],
        default: 2,
        path: `LAYER #/PLAY MODE/Value`,
        unit: '',
    },
    {
        name: 'framingmode',
        type: 'select',
        label: 'Framing Mode',
        options: [
            { value: 0, label: 'Letterbox' },
            { value: 1, label: 'Crop' },
            { value: 2, label: 'Stretch' },
            { value: 3, label: 'Multi Letterbox' },
            { value: 4, label: 'Centred' },
        ],
        default: 0,
        path: `LAYER #/FRAMING MODE/Value`,
        unit: '',
    },
    {
        name: 'blendmode',
        type: 'select',
        label: 'Blend Mode',
        options: [
            { value: 0, label: 'Alpha' },
            { value: 1, label: 'Additive' },
            { value: 2, label: 'Multiply' },
            { value: 3, label: 'Difference' },
            { value: 4, label: 'Screen' },
            { value: 5, label: 'Preserve Luma' },
            { value: 6, label: 'Rectangle Wipe' },
            { value: 7, label: 'Triangle Wipe' },
        ],
        default: 0,
        path: `LAYER #/BLEND MODE/Value`,
        unit: '',
    },
    {
        name: 'lut',
        type: 'integer',
        label: 'L,U,T Select',
        min: 0,
        max: 100,
        default: 0.0,
        defaultstep: 1,
        path: `LAYER #/LUT/Value`,
        unit: '',
    },
    {
        name: 'playspeed',
        type: 'range',
        label: 'Play Speed',
        min: 0,
        max: 1000,
        default: 0.5,
        defaultstep: 10,
        path: `LAYER #/PLAY SPEED/Value`,
        unit: '%',
    },
    {
        name: 'movementspeed',
        type: 'integer',
        label: 'Movement Speed',
        min: 0,
        max: 100,
        default: 0.0,
        defaultstep: 1,
        path: `LAYER #/MOVEMENT SPEED/Value`,
        unit: '%',
    },
    {
        name: 'tchour',
        type: 'integer',
        label: 'Timecode Hour',
        min: 0,
        max: 23,
        default: 0.0,
        defaultstep: 1,
        path: `LAYER #/MTC HOUR/Value`,
        unit: 'hr',
    },
    {
        name: 'tcminute',
        type: 'integer',
        label: 'Timecode Minute',
        min: 0,
        max: 59,
        default: 0.0,
        defaultstep: 1,
        path: `LAYER #/MTC MINUTE/Value`,
        unit: 'min',
    },
    {
        name: 'tcsecond',
        type: 'integer',
        label: 'Timecode Second',
        min: 0,
        max: 59,
        default: 0.0,
        defaultstep: 1,
        path: `LAYER #/MTC SECOND/Value`,
        unit: 'sec',
    },
    {
        name: 'tcframe',
        type: 'integer',
        label: 'Timecode Frame',
        min: 0,
        max: 29,
        default: 0.0,
        defaultstep: 1,
        path: `LAYER #/MTC FRAME/Value`,
        unit: 'fr',
    },
    {
        name: 'scale',
        type: 'range',
        label: 'Scale',
        min: 0,
        max: 1000,
        default: 0.5,
        defaultstep: 10,
        path: `LAYER #/SCALE/Value`,
        unit: '%',
    },
    {
        name: 'aspect',
        type: 'range',
        label: 'Aspect',
        min: 0,
        max: 100,
        default: 0.0,
        defaultstep: 1,
        path: `LAYER #/ASPECT RATIO/Value`,
        unit: '',
    },
    {
        name: 'posx',
        type: 'range',
        label: 'X Position',
        min: -100,
        max: 100,
        default: 0.5,
        defaultstep: 10,
        path: `LAYER #/POSITION X/Value`,
        unit: '%',
    },
    {
        name: 'posy',
        type: 'range',
        label: 'Y Position',
        min: -100,
        max: 100,
        default: 0.5,
        defaultstep: 10,
        path: `LAYER #/POSITION Y/Value`,
        unit: '%',
    },
    {
        name: 'rotx',
        type: 'range',
        label: 'X Rotation',
        min: -1440,
        max: 1440,
        default: 0.5,
        defaultstep: 10,
        path: `LAYER #/ROTATION X/Value`,
        unit: 'deg',
    },
    {
        name: 'roty',
        type: 'range',
        label: 'Y Rotation',
        min: -1440,
        max: 1440,
        default: 0.5,
        defaultstep: 10,
        path: `LAYER #/ROTATION Y/Value`,
        unit: 'deg',
    },
    {
        name: 'rotz',
        type: 'range',
        label: 'Z Rotation',
        min: -1440,
        max: 1440,
        default: 0.5,
        defaultstep: 10,
        path: `LAYER #/ROTATION Z/Value`,
        unit: 'deg',
    },
    {
        name: 'red',
        type: 'range',
        label: 'Red',
        min: -100,
        max: 100,
        default: 0.5,
        defaultstep: 10,
        path: `LAYER #/RED/Value`,
        unit: '%',
    },
    {
        name: 'green',
        type: 'range',
        label: 'Green',
        min: -100,
        max: 100,
        default: 0.5,
        defaultstep: 10,
        path: `LAYER #/GREEN/Value`,
        unit: '%',
    },
    {
        name: 'blue',
        type: 'range',
        label: 'Blue',
        min: -100,
        max: 100,
        default: 0.5,
        defaultstep: 10,
        path: `LAYER #/BLUE/Value`,
        unit: '%',
    },
    {
        name: 'hue',
        type: 'range',
        label: 'HUE',
        min: 0,
        max: 100,
        default: 0.0,
        defaultstep: 1,
        path: `LAYER #/HUE/Value`,
        unit: '',
    },
    {
        name: 'saturation',
        type: 'range',
        label: 'Saturation',
        min: -100,
        max: 100,
        defaultstep: 1,
        default: 0.5,
        path: `LAYER #/SATURATION/Value`,
        unit: '',
    },
    {
        name: 'contrast',
        type: 'range',
        label: 'Contrast',
        min: -100,
        max: 100,
        default: 0.5,
        defaultstep: 1,
        path: `LAYER #/CONTRAST/Value`,
        unit: '',
    },
    {
        name: 'strobe',
        type: 'range',
        label: 'Strobe',
        min: 0,
        max: 100,
        default: 0.0,
        defaultstep: 10,
        path: `LAYER #/STROBE/Value`,
        unit: '',
    },
    {
        name: 'volume',
        type: 'range',
        label: 'Volume',
        min: 0,
        max: 100,
        default: 1.0,
        defaultstep: 10,
        path: `LAYER #/VOLUME/Value`,
        unit: '%',
    },
    {
        name: 'frameblending',
        type: 'select',
        label: 'Frame Blending',
        options: [
            { value: 0, label: 'Disabled' },
            { value: 1, label: 'Enabled' },
        ],
        default: 1.0,
        path: `LAYER #/FRAME BLENDING/Value`,
        unit: '',
    },
    {
        name: 'transitionduration',
        type: 'integer',
        label: 'Transition Duration',
        min: 0,
        max: 65535,
        default: 0,
        defaultstep: 10,
        path: `LAYER #/TRANSITION DURATION/Value`,
        unit: 'ms',
    },
    {
        name: 'transitionmode',
        type: 'select',
        label: 'Transition Mode',
        options: [
            { value: 0, label: 'Alpha' },
            { value: 1, label: 'Additive' },
            { value: 2, label: 'Multiply' },
            { value: 3, label: 'Difference' },
            { value: 4, label: 'Screen' },
            { value: 5, label: 'Preserve Luma' },
            { value: 6, label: 'Rectangle Wipe' },
            { value: 7, label: 'Triangle Wipe' },
            { value: 8, label: 'Minimum' },
            { value: 9, label: 'Maximum' },
            { value: 10, label: 'Subtract' },
            { value: 11, label: 'Darken' },
            { value: 12, label: 'Lighten' },
            { value: 13, label: 'Soft Lighten' },
            { value: 14, label: 'Dark Lighten' },
            { value: 15, label: 'Exclusion' },
            { value: 16, label: 'Random' },
            { value: 17, label: 'Ripple' },
            { value: 18, label: 'Threshold' },
            { value: 19, label: 'Sine' },
            { value: 20, label: 'Invert Mask' },
            { value: 21, label: 'Noise' },
            { value: 22, label: 'Swirl' },
            { value: 23, label: 'Gradient' },
            { value: 24, label: 'Pixel Sort' },
            { value: 25, label: 'Checkerboard' },
            { value: 26, label: 'Pulse' },
            { value: 27, label: 'Hue Shift' },
            { value: 28, label: 'Fractal' },
            { value: 29, label: 'Waveform' },
            { value: 30, label: 'RGB Split' },
            { value: 31, label: 'Glitch' },
        ],
        default: 0,
        path: `LAYER #/TRANSITION MODE/Value`,
        unit: '',
    },
]